### ISSUE TITLE
add some badges to the README

### ISSUE THREAD

**Issue by Umesh-01** [LetsGrowMoreCommunity/DSA-Playyard#10]
## Description
Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help the users to navigate to different sections/ webpages like PRs, issues, contributors, etc.

![image](https://user-images.githubusercontent.com/83420185/125986956-fe2db87e-9ee6-4515-bd32-deb86fd59364.png)

## Solution 
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

## Work under/as
 - [x] LGMSOC
 - [x] Contributor

**Comment by Umesh-01** [comment]
@vnmrsharma @rohan-kulkarni-25 should I work on this??

**Comment by Sargam-Agarwal** [comment]
Hey @Umesh-01 , the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
Keep Coding :)
