### ISSUE TITLE
Add Two Numbers(Linked List)

### ISSUE THREAD

**Issue by Ayonijakaushik19** [LetsGrowMoreCommunity/DSA-Playyard#101]
Contribution Guidelines for this question-

-Languages available: C++, Java, Python
-Well Commented Code
-In the starting, add a brief explanation of the algorithm
-if possible, add time and space complexity
-kindly upload your code in TREES -> Language (C++, Java, Python) Folder
-NO PLAGIARISM

**Comment by ujju20** [comment]
Hey, @Ayonijakaushik19  In the Readme file it is clearly mentioned that the issues are to be created by mentors only.
The Participants can suggest the questions.

So Kindly Close all the issues created by you by tonight.
