### ISSUE TITLE
Add the appropriate license in the README 

### ISSUE THREAD

**Issue by Umesh-01** [LetsGrowMoreCommunity/DSA-Playyard#11]
## Description 
Add the appropriate license In the README

## Solution
I will add a appropriate license according to your choice.

## Improvements suggested
Use https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository to learn about licenses.

**Comment by Umesh-01** [comment]
@vnmrsharma @rohan-kulkarni-25 should I add a license??

**Comment by Sargam-Agarwal** [comment]
Hey @Umesh-01  , the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file. No participant can open an issue for any question. You can suggest the questions. Please check out README.md for more.
Keep Coding :)
