### ISSUE TITLE
Finding the largest in an array 

### ISSUE THREAD

**Issue by nisha331** [LetsGrowMoreCommunity/DSA-Playyard#12]
Hey @vilsi12 i would  like to would on this issue and would like to add the file in the c++ folder. I would be great if you could assign it to me (LGMSOC 21).

**Comment by SnehaAgarwal361** [comment]
Hey @nisha331  , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
Once we post questions there you can contribute, for now closing the issue!
Keep Coding :)
