### ISSUE TITLE
Find the kth largest element using heap

### ISSUE THREAD

**Issue by ChetasShree** [LetsGrowMoreCommunity/DSA-Playyard#13]
hi, I want to solve this issue using C++
Please assign this issue to me under LGMSoC  .
Looking forward to contribute here...
Question link: https:https://leetcode.com/problems/kth-largest-element-in-an-array/

**Comment by SnehaAgarwal361** [comment]
Hey @ChetasShree ,  the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
Once we post questions there you can contribute!
Keep Coding :)
