### ISSUE TITLE
kadane's algorithm

### ISSUE THREAD

**Issue by rahulsrivastava1** [LetsGrowMoreCommunity/DSA-Playyard#14]
i want to contribute a code of kadane's algorithm in array in cpp

**Comment by comnk** [comment]
can I do this in Java or Python?

**Comment by SnehaAgarwal361** [comment]
Hey @rahulsrivastava1  , the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
Once we post questions there we can contribute!
Keep Coding :)
