### ISSUE TITLE
1. Reverse Linked List (LINKED LIST)

### ISSUE THREAD

**Issue by Sargam-Agarwal** [LetsGrowMoreCommunity/DSA-Playyard#15]
Contribution Guidelines for this question
 
- Languages available : C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in LINKED LIST -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by gunjan-g** [comment]
I want to work on this issue, please assign

**Comment by gunjan-g** [comment]
@sameeksharl @Sargam-Agarwal

**Comment by sameeksharl** [comment]
okay please do follow the guidelines and complete the work within 3/4 days

**Comment by gunjan-g** [comment]
> okay please do follow the guidelines and complete the work within 3/4 days

sure

**Comment by SnehaAgarwal361** [comment]
Hey @gunjan-g , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
Once we post questions there you can contribute, for now closing the issue!
Keep Coding :)

**Comment by gunjan-g** [comment]
> Hey @gunjan-g , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
> We are going to be starting afresh. So, as of now, you cannot contribute the code for this question. You can do it once we open a new issue for it.
> Really sorry for any inconvenience.
> Keep Coding :)

ok di
