### ISSUE TITLE
find the first duplicate element in a given array of integers

### ISSUE THREAD

**Issue by sameeksharl** [LetsGrowMoreCommunity/DSA-Playyard#17]
Contribution Guidelines for this question

- Languages available : C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add testcases .
- if possible, add time and space complexity
- kindly upload your code in Arrays -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by sameeksharl** [comment]
Input 
1, 2, 3, 4, 4, 5
1, 2, 3, 4
1, 1, 2, 3, 3, 2, 2

Output
4
-1
1

**Comment by gunjan-g** [comment]
@sameeksharl please assign me this issue in C++

**Comment by sameeksharl** [comment]
Pls come back after making the pr for the assigned issue

**Comment by chandu6111** [comment]
Hey, @sameeksharl I would like to contribute to this issue in python under LGMSOC'21. Could you please assign this issue to me?
- [x] python

**Comment by sameeksharl** [comment]
Hey @chandu6111  , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
