### ISSUE TITLE
program to sort the given array

### ISSUE THREAD

**Issue by sameeksharl** [LetsGrowMoreCommunity/DSA-Playyard#19]
Contribution Guidelines for this question

- Languages available : C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add testcases .
- if possible, add time and space complexity
- kindly upload your code in Arrays -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by gunjan-g** [comment]
@sameeksharl please assign me this issue in C++

**Comment by siddhi-244** [comment]
Can I try in python?

**Comment by gunjan-g** [comment]
@sameeksharl, I've completed my task, please assign me this issue

**Comment by 2000shivam659** [comment]
I would like to try this in **Java**.

**Comment by gunjan-g** [comment]
@sameeksharl Please assign me this issue in C++

**Comment by nisha331** [comment]
Hey mentors and project admin the project has been revampes so kindly assign this issue to  to me in c++ .

**Comment by sameeksharl** [comment]
Hey @gunjan-g @nisha331 @siddhi-244  , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
