### ISSUE TITLE
find k’th Smallest and Largest Element in Unsorted Array

### ISSUE THREAD

**Issue by sameeksharl** [LetsGrowMoreCommunity/DSA-Playyard#20]
Contribution Guidelines for this question

- Languages available : C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add testcases .
- if possible, add time and space complexity
- kindly upload your code in Arrays -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by gunjan-g** [comment]
@sameeksharl I want to work on this issue, please assign me this

**Comment by gunjan-g** [comment]
@sameeksharl completed my task, please assign me this issue

**Comment by sonamgupta136** [comment]
@sameeksharl  I want to try in c++

**Comment by gunjan-g** [comment]
@sameeksharl Please assign me this issue in C++

**Comment by sameeksharl** [comment]
Hey @gunjan-g @sonamgupta136  , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
