### ISSUE TITLE
Count leaf nodes in a binary tree

### ISSUE THREAD

**Issue by sameeksharl** [LetsGrowMoreCommunity/DSA-Playyard#21]
Contribution Guidelines for this question

- Languages available : C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add testcases .
- if possible, add time and space complexity
- kindly upload your code in Binary Trees -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by vchsi** [comment]
Hi @sameeksharl ,
I am a first time contributor and I have done a lot of Leetcode DSA Problems. May I be assigned this issue for python3?

**Comment by sameeksharl** [comment]
Sure go ahead @vchsi

**Comment by vchsi** [comment]
Hi @sameeksharl ,
When I am finished with this issue, do I need to make a pull request or do I just upload it right into the folder?

**Comment by sameeksharl** [comment]
No u have to make a pull request.  I think u know how to do it.
Fork ,commit ur work , and then make pr

**Comment by vchsi** [comment]
Ok, I will do that when I am finished with my code.

**Comment by vchsi** [comment]
I am done with my code and have made a Pull Request.

**Comment by sameeksharl** [comment]
Hey @vchsi  , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
