### ISSUE TITLE
9.Split Linked List in Parts (LINKED LIST)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#212]
# Contribution Guidelines for this question-

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in Linked List -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

**Comment by soma2000-lang** [comment]
@ujju20  PLease assign me this issue.I will code in C++.I am a LGM SOC partucipant

**Comment by ujju20** [comment]
Sure, Do follow the guidelines and complete your work in 2 days.
One more thing don't take more than two issues at a time.

**Comment by 2000shivam659** [comment]
I would like to sloe this in **java** language.

**Comment by 2000shivam659** [comment]
> I would like to sloe this in **java** language.

Please assign me this issue...
