### ISSUE TITLE
2.Merge Two sorted linked list (LINKED LIST)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#22]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Linked List -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by comnk** [comment]
Hello @ujju20 

I am a first time contributor who has worked on LeetCode challenges and problems for a while now. Can I work on this issue?

**Comment by gunjan-g** [comment]
@ujju20 please assign me this issue in C++

**Comment by ujju20** [comment]
> Hello @ujju20
> 
> I am a first time contributor who has worked on LeetCode challenges and problems for a while now. Can I work on this issue in Java or Python?

Choose one Language

**Comment by ujju20** [comment]
> @ujju20 please assign me this issue in C++

@gunjan-g  One person can work at max 2 issues so first try the issues you have assigned then come and grad new issues.

**Comment by gunjan-g** [comment]
> > @ujju20 please assign me this issue in C++
> 
> @gunjan-g One person can work at max 2 issues so first try the issues you have assigned then come and grad new issues.

Ok, I'll complete them by today

**Comment by ujju20** [comment]
> > > @ujju20 please assign me this issue in C++
> > 
> > 
> > @gunjan-g One person can work at max 2 issues so first try the issues you have assigned then come and grad new issues.
> 
> Ok, I'll complete them by today

Ya First Complete those issues then grab the new ones.

**Comment by comnk** [comment]
Can I work on this issue in Java?

**Comment by ujju20** [comment]
> Can I work on this issue in Java?

Ok Do follow the guidelines and complete your work in 2/3 days.

**Comment by comnk** [comment]
Do I need to build a LinkedList class alongside with the code?

**Comment by ujju20** [comment]
> Do I need to build a LinkedList class alongside with the code?

Yes You have to

**Comment by gunjan-g** [comment]
> > > > @ujju20 please assign me this issue in C++
> > > 
> > > 
> > > @gunjan-g One person can work at max 2 issues so first try the issues you have assigned then come and grad new issues.
> > 
> > 
> > Ok, I'll complete them by today
> 
> Ya First Complete those issues then grab the new ones.

I've completed one of them, now could you assign me this in C++

**Comment by comnk** [comment]
should it work with a certain type (whether it be ints or strings or floats), or all types?

**Comment by ujju20** [comment]
Hey Guys, the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
