### ISSUE TITLE
3.Find Length of a Linked List (LINKED LIST)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#23]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Linked List -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by gunjan-g** [comment]
@ujju20 please assign me this issue in C++

**Comment by ujju20** [comment]
> @ujju20 please assign me this issue in C++

@gunjan-g One person can work at max 2 issues so first try the issues you have assigned then come and grad new issues.

**Comment by gunjan-g** [comment]
> > @ujju20 please assign me this issue in C++
> 
> @gunjan-g One person can work at max 2 issues so first try the issues you have assigned then come and grad new issues.

I've done my task, please assign me this

**Comment by chandu6111** [comment]
Hey @ujju20 I would like to contribute to this issue under LGMSOC'21 in C++
Could you please assign me this issue?

- [x] C++

**Comment by ujju20** [comment]
Hey Guys, the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
