### ISSUE TITLE
4. Find the middle Element of a given Linked List (LINKED LIST)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#24]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Linked List -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by comnk** [comment]
Can I contribute to this issue?

**Comment by comnk** [comment]
In Java or Python, whichever works for you

**Comment by ujju20** [comment]
> In Java or Python, whichever works for you

choose one

**Comment by ChetasShree** [comment]
I want to solve this issue using C++
Please assign this issue to me under LGMSoC .
Looking forward to contribute here... @ujju20

**Comment by ujju20** [comment]
Hey Guys, the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
