### ISSUE TITLE
Find the frequency of a number in an array

### ISSUE THREAD

**Issue by drishtibaranwal** [LetsGrowMoreCommunity/DSA-Playyard#242]
# Contribution Guidelines for this question-

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in <Folder Name> -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

**Comment by drishtibaranwal** [comment]
I want to work on this issue. I want to do this problem in C++ in array section. Please assign me this issue.

**Comment by YashThakare** [comment]
> I want to work on this issue. I want to do this problem in C++ in array section. Please assign me this issue.

Hello @drishtibaranwal , In the README file it is clearly mentioned that the issues are to be created by mentors only.
Participants can suggest the questions. Please go through README file.

So kindly close all the issues created by you by tonight.
