### ISSUE TITLE
Union and Intersection of two sorted arrays in C++ 

### ISSUE THREAD

**Issue by drishtibaranwal** [LetsGrowMoreCommunity/DSA-Playyard#243]
# Contribution Guidelines for this question-

- Languages available: C++, Java, Python
- Well Commented Code
- In the starting, add a brief explanation of the algorithm
- if possible, add time and space complexity
- kindly upload your code in <Folder Name> -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

**Comment by drishtibaranwal** [comment]
I want to work on this issue. I want to solve this problem in C++. Please assign me this issue.

**Comment by Sargam-Agarwal** [comment]
Hey @drishtibaranwal,
Kindly read the README thoroughly. Its clearly mentioned there that participants cannot and are not supposed to create issues under any circumstance.  
Kindly close all the issues that you have created and take care of it from next time onwards.
