### ISSUE TITLE
5.Detect Loop in a Linked List (LINKED LIST)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#25]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Linked List -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by gunjan-g** [comment]
@ujju20 please assign me this issue in C++

**Comment by ujju20** [comment]
Ya Sure 
Do follow the guidelines and Complete your work in 2/3 days.

**Comment by gunjan-g** [comment]
> Ya Sure
> Do follow the guidelines and Complete your work in 2/3 days.

ok sure

**Comment by gunjan-g** [comment]
@ujju20 do we have to write the full code or just the function

**Comment by ujju20** [comment]
> @ujju20 do we have to write the full code or just the function

Full code

**Comment by gunjan-g** [comment]
> > @ujju20 do we have to write the full code or just the function
> 
> Full code

thanks

**Comment by 2000shivam659** [comment]
Could you please assign me this under **Java** language.

**Comment by ujju20** [comment]
Hey Guys, the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
