### ISSUE TITLE
1. Reverse Bits of a Given Binary Number (BIT-MANIPULATION)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#26]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by mrkc2303** [comment]
I can do this in C++. Kindly assign me!

**Comment by ujju20** [comment]
Hey @mrkc2303, the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
