### ISSUE TITLE
2.Count set bits in a number (BIT-MANIPULATION)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#27]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation-> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by 2000shivam659** [comment]
I have solved this one, please allow me to do this in **Java** language.

**Comment by ujju20** [comment]
Hey @2000shivam659 , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
