### ISSUE TITLE
4.Calculate square of a number without using *, / and pow() (BIT-MANIPULATION)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#29]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by Sanskriti2401** [comment]
@ujju20 I want to work on this issue in C++ language.

**Comment by 2000shivam659** [comment]
I would like to try this under **Java** language, Please assign me this.

**Comment by ujju20** [comment]
Hey @Sanskriti2401 @2000shivam659 , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
