### ISSUE TITLE
5.Count total set bits from 1 to N (BIT-MANIPULATON)

### ISSUE THREAD

**Issue by ujju20** [LetsGrowMoreCommunity/DSA-Playyard#30]
# Contribution Guidelines for this question

- Languages available: C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add test cases.
- if possible, add time and space complexity
- kindly upload your code in Bit-Manipulation -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by nisha331** [comment]
Hey mentors and Project admins i would like to work on this issue in c++ language kindly assign it to me.

**Comment by nisha331** [comment]
Hey mentors and Project admins i would like to work on this issue in c++ language kindly assign it to me.

**Comment by 2000shivam659** [comment]
Please assign me this under Java language....

**Comment by yellowberard** [comment]
I would like to solve this question with C++ Language. Kindly Assign me his issue.

**Comment by ujju20** [comment]
Hey @2000shivam659 @nisha331 @yellowberard , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
