### ISSUE TITLE
Add Contribution Guidelines for this project as well the Contribution Guidelines for the questions in the README.MD file itself.

### ISSUE THREAD

**Issue by Ayonijakaushik19** [LetsGrowMoreCommunity/DSA-Playyard#35]
Hi, @vilsi12 please assign this to me.

**Comment by Sargam-Agarwal** [comment]
Hey @Ayonijakaushik19, the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
Keep Coding :)
