### ISSUE TITLE
implement tree traversal (iterative method which should include preorder, inorder , postorder) 

### ISSUE THREAD

**Issue by sameeksharl** [LetsGrowMoreCommunity/DSA-Playyard#39]
Contribution Guidelines for this question

- Languages available : C++, Java, Python (please do mention in which language you will be implementing)
- Well Commented Code
- In the starting, add a brief explanation of the algorithm and at the end, add testcases .
- if possible, add time and space complexity
- kindly upload your code in Binary Trees -> Language (C++, Java, Python) Folder
- NO PLAGIARISM

**Comment by 2000shivam659** [comment]
Please assign me this in **Java** language. I will upload sol. within 1-2 days.

**Comment by sameeksharl** [comment]
Hey  @2000shivam659 , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now.
We are going to be starting afresh. You can wait until the opening of new issues.
Really sorry for any inconvenience.
Keep Coding :)
