### ISSUE TITLE
Merge k sorted list.

### ISSUE THREAD

**Issue by anushka-srivastava22** [LetsGrowMoreCommunity/DSA-Playyard#43]
This is a hard level problem but an important concept. I would like to contribute my solution using java languge as I am a lgmsoc participant so kindly assign this issue to me under lgmsoc tag.
@mentors @rohan-kulkarni-25 @Sargam-Agarwal

**Comment by Sargam-Agarwal** [comment]
Hey @anushka-srivastava22, the contribution guidelines have been updated. Kindly check them. Participants cannot open the issue. Thus, closing this one. 
Keep Coding :)
