### ISSUE TITLE
Rain Water Trapping

### ISSUE THREAD

**Issue by anushka-srivastava22** [LetsGrowMoreCommunity/DSA-Playyard#44]
This is a hard level problem but an important concept. This problem is asked in almost every interview and coding rounds. I would like to contribute my solution using java languge to this problem. Kindly assign me this issue under lgmsoc tag.
@mentors @rohan-kulkarni-25 @Sargam-Agarwal

**Comment by SnehaAgarwal361** [comment]
Hey @anushka-srivastava22  , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
We are going to be starting afresh. So, as of now, you cannot contribute the code for this question. You can do it once we open a new issue for it.
Really sorry for any inconvenience.
Keep Coding :)

**Comment by anushka-srivastava22** [comment]
Ya ya it okay ...  I came to know about it and hence i closed one issue myself.
