### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by 2000shivam659** [LetsGrowMoreCommunity/DSA-Playyard#45]
### Aim

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

##Details

<img width="713" alt="3" src="https://user-images.githubusercontent.com/76156804/126107628-5fb9742b-c2c6-412a-aa53-3206f0dc5535.png">

### Programing language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by 2000shivam659** [comment]
Please assign me this under LGMSOC'21.

**Comment by Sargam-Agarwal** [comment]
Hey @2000shivam659 , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant can open an issue for any question.
We are going to be starting afresh. So, as of now, you cannot contribute the code for this question. You can do it once we open a new issue for it.
Really sorry for any inconvenience.
Keep Coding :)
