### ISSUE TITLE
Remove Nth Node From End of List

### ISSUE THREAD

**Issue by 2000shivam659** [LetsGrowMoreCommunity/DSA-Playyard#46]
### Aim

Given the head of a linked list, remove the nth node from the end of the list and return its head.

### Details

<img width="642" alt="3" src="https://user-images.githubusercontent.com/76156804/126108107-85443bef-41c8-47dc-a23e-98477de41f40.png">

### Programing language

- [ ] 
- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

**Comment by 2000shivam659** [comment]
@Sargam-Agarwal Please assign me this under LGMSOC'21.

**Comment by Sargam-Agarwal** [comment]
Hey @2000shivam659 , the project has undergone a major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant can open an issue for any question.
We are going to be starting afresh. So, as of now, you cannot contribute the code for this question. You can do it once we open a new issue for it.
Really sorry for any inconvenience.
Keep Coding :)
