### ISSUE TITLE
Create a Array 

### ISSUE THREAD

**Issue by vilsi12** [LetsGrowMoreCommunity/DSA-Playyard#5]
For asking to assign 
I want to this question of 'Topic' in Language
Python ,Java etc
We will be assigning you 

https://youtu.be/Ff38VOjv1no

**Comment by nisha331** [comment]
Hey @vilsi12 I would like to work on this issue and create an array in C++ language. I would be great if you could assign it to me .

**Comment by siddhi-244** [comment]
I would like to try in python under lgmsoc

**Comment by Sargam-Agarwal** [comment]
Hey @nisha331, @siddhi-244, the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it. 
As of now then, you shouldn't work on this issue as we are starting afresh. 
Really sorry for the inconvenience. 
Keep Coding :)
