### ISSUE TITLE
Maximum XOR of two array

### ISSUE THREAD

**Issue by neha030** [LetsGrowMoreCommunity/DSA-Playyard#6]
Given an integer array nums, return the maximum result of nums[i] XOR nums[j], 
where 0 ≤ i ≤ j < n.

I want to provide the code in C++ language in Bit-Manipulation Folder
Please assign me this issue

https://youtu.be/Ff38VOjv1no

**Comment by 2000shivam659** [comment]
Can I try in java ?

**Comment by neha030** [comment]
I want to add this question of "Array" in Language C++
Please assign me

**Comment by 2000shivam659** [comment]
I want to add this question of "Array" in Java Language.
Please assign me this issue.

**Comment by Sargam-Agarwal** [comment]
Hey @neha030 @2000shivam659, the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it.
No participant can open an issue for any question. You can suggest the questions. Please check out README.md for more.
Keep Coding :)
