### ISSUE TITLE
Reverse Circular Linked list

### ISSUE THREAD

**Issue by neha030** [LetsGrowMoreCommunity/DSA-Playyard#7]
I want to provide the code in C++ language 
Please assign me this issue

**Comment by 2000shivam659** [comment]
I would like to solve this in java language. Please assign me this issue.

**Comment by vilsi12** [comment]
For asking to assign
I want to this question of 'Topic' in Language
Python ,Java etc
We will be assigning you

https://youtu.be/Ff38VOjv1no

**Comment by neha030** [comment]
> For asking to assign
> I want to this question of 'Topic' in Language
> Python ,Java etc
> We will be assigning you
> 
> https://youtu.be/Ff38VOjv1no

I want to add this question of "Linked List" in Language C++
Please assign me

**Comment by 2000shivam659** [comment]
> For asking to assign
> I want to this question of 'Topic' in Language
> Python ,Java etc
> We will be assigning you
> 
> https://youtu.be/Ff38VOjv1no

I want to add this question of "Linked List" in Java Language.
Please assign me this issue.

**Comment by Sargam-Agarwal** [comment]
Hey @neha030 @2000shivam659 , the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it.
As of now, closing this issue. 
Keep Coding :)
