### ISSUE TITLE
Longest Substring Without Repeating Character

### ISSUE THREAD

**Issue by devanshi-code** [LetsGrowMoreCommunity/DSA-Playyard#8]
I want to add  this 'Longest Substring Without Repeating Character' in C++ language

**Comment by Sargam-Agarwal** [comment]
Hey @devanshi-code , the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
No participant can open an issue for any question. You can suggest the questions. Please check out README.md for more.
Keep Coding :)
