### ISSUE TITLE
4. Trapping Rain Water (DYNAMIC PROGRAMMING)

### ISSUE THREAD

**Issue by YashThakare** [LetsGrowMoreCommunity/DSA-Playyard#83]
Contribution Guidelines for this question

-Languages available: C++, Java, Python
-Well Commented Code
-In the starting, add a brief explanation of the algorithm
-if possible, add time and space complexity
-kindly upload your code in DYNAMIC PROGRAMMING -> Language (C++, Java, Python) Folder
-NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

**Comment by khushi-purwar** [comment]
Kindly assign me this issue under LGMSOC'21 @YashThakare . I want to work on this issue in C++.

**Comment by YashThakare** [comment]
> Kindly assign me this issue under LGMSOC'21 @YashThakare . I want to work on this issue in C++.

Hi @khushi-purwar , Do follow the guidelines and complete your work in 2 days. Please go through README file.

**Comment by siddhi-244** [comment]
Can I try in python?

**Comment by YashThakare** [comment]
> Can I try in python?

Hi @siddhi-244 , Do follow the guidelines and complete your work in 2 days. Please go through README file.

**Comment by 2000shivam659** [comment]
Please assign me this in **java** language.

**Comment by YashThakare** [comment]
> Please assign me this in **java** language.

Hi @2000shivam659  , Do follow the guidelines and complete your work in 2 days. Please go through README file.
