### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by swathi-469** [LetsGrowMoreCommunity/DSA-Playyard#9]
I would to add step by step instructions for the Beginners in the open source with links , resources , sample screenshots and links to download before contribution. Please assign me

**Comment by Sargam-Agarwal** [comment]
Hey @swathi-469 , the project has undergone major restructuring so we have updated our README along with the contribution guidelines and some other important points. Kindly check it and as of now, no participant is supposed to update the README.md file.
Keep Coding :)
