### ISSUE TITLE
4. Excel Sheet Column Title (MATH)

### ISSUE THREAD

**Issue by YashThakare** [LetsGrowMoreCommunity/DSA-Playyard#90]
Contribution Guidelines for this question

-Languages available: C++, Java, Python
-Well Commented Code
-In the starting, add a brief explanation of the algorithm
-if possible, add time and space complexity
-kindly upload your code in MATH -> Language (C++, Java, Python) Folder
-NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

**Comment by AtrikGit6174** [comment]
I would like to add the C++ solution for this problem under LGMSOC21. Kindly assign me this issue.

**Comment by YashThakare** [comment]
> I would like to add the C++ solution for this problem under LGMSOC21. Kindly assign me this issue.

Do follow the guidelines and complete your work in 1 day. Please go through README file.

**Comment by sumitsoni0907** [comment]
I would like to add the java solution for this problem under LGMSOC21.
please assign me.

**Comment by YashThakare** [comment]
> I would like to add the java solution for this problem under LGMSOC21.
> please assign me.

Hi @sumitsoni0907 , Do follow the guidelines and complete your work in 1 day. Please go through README file.

**Comment by sumitsoni0907** [comment]
> Hi @sumitsoni0907 , Do follow the guidelines and complete your work in 1 day. Please go through README file.

ok

**Comment by sumitsoni0907** [comment]
> Contribution Guidelines for this question
> 
> -Languages available: C++, Java, Python
> -Well Commented Code
> -In the starting, add a brief explanation of the algorithm
> -if possible, add time and space complexity
> -kindly upload your code in MATH -> Language (C++, Java, Python) Folder
> -NO PLAGIARISM
> 
> Also, watch this video and the README section before contributing to the project.
> https://youtu.be/qXeaN_ZVVIc

I would also like to add python solution for this problem under LGMSOC21. Please assign me.

**Comment by YashThakare** [comment]
> > Contribution Guidelines for this question
> > -Languages available: C++, Java, Python
> > -Well Commented Code
> > -In the starting, add a brief explanation of the algorithm
> > -if possible, add time and space complexity
> > -kindly upload your code in MATH -> Language (C++, Java, Python) Folder
> > -NO PLAGIARISM
> > Also, watch this video and the README section before contributing to the project.
> > https://youtu.be/qXeaN_ZVVIc
> 
> I would also like to add python solution for this problem under LGMSOC21. Please assign me.

Hi @sumitsoni0907 , Do follow the guidelines and complete your work in 1 day. Please go through README file.
