### ISSUE TITLE
5. Factorial Trailing Zeroes (MATH)

### ISSUE THREAD

**Issue by YashThakare** [LetsGrowMoreCommunity/DSA-Playyard#91]
Contribution Guidelines for this question

-Languages available: C++, Java, Python
-Well Commented Code
-In the starting, add a brief explanation of the algorithm
-if possible, add time and space complexity
-kindly upload your code in MATH -> Language (C++, Java, Python) Folder
-NO PLAGIARISM

Also, watch this video and the README section before contributing to the project.
https://youtu.be/qXeaN_ZVVIc

**Comment by khushi-purwar** [comment]
> Contribution Guidelines for this question
> 
> -Languages available: C++, Java, Python
> -Well Commented Code
> -In the starting, add a brief explanation of the algorithm
> -if possible, add time and space complexity
> -kindly upload your code in MATH -> Language (C++, Java, Python) Folder
> -NO PLAGIARISM
> 
> Also, watch this video and the README section before contributing to the project.
> https://youtu.be/qXeaN_ZVVIc

I want to work in this issue, please assign  it to me @YashThakare

**Comment by YashThakare** [comment]
> > Contribution Guidelines for this question
> > -Languages available: C++, Java, Python
> > -Well Commented Code
> > -In the starting, add a brief explanation of the algorithm
> > -if possible, add time and space complexity
> > -kindly upload your code in MATH -> Language (C++, Java, Python) Folder
> > -NO PLAGIARISM
> > Also, watch this video and the README section before contributing to the project.
> > https://youtu.be/qXeaN_ZVVIc
> 
> I want to work on this issue in C++, please assign it to me @YashThakare

Hello @khushi-purwar , Do follow the guidelines and complete your work in 1 day. Please go through README file.

**Comment by khushi-purwar** [comment]
ok

> > > Contribution Guidelines for this question
> > > -Languages available: C++, Java, Python
> > > -Well Commented Code
> > > -In the starting, add a brief explanation of the algorithm
> > > -if possible, add time and space complexity
> > > -kindly upload your code in MATH -> Language (C++, Java, Python) Folder
> > > -NO PLAGIARISM
> > > Also, watch this video and the README section before contributing to the project.
> > > https://youtu.be/qXeaN_ZVVIc
> > 
> > 
> > I want to work on this issue in C++, please assign it to me @YashThakare
> 
> Hello @khushi-purwar , Do follow the guidelines and complete your work in 1 day. Please go through README file.

ok

**Comment by 2000shivam659** [comment]
Please assign me this in **java** language.

**Comment by YashThakare** [comment]
> Please assign me this in **java** language.

Hello @2000shivam659  , Do follow the guidelines and complete your work in 1 day. Please go through README file.

**Comment by sumitsoni0907** [comment]
please assign me this in python language.

**Comment by YashThakare** [comment]
> please assign me this in python language.

Hi @sumitsoni0907 , Do follow the guidelines and complete your work in 1 day. Please go through README file.

**Comment by sumitsoni0907** [comment]
> Hi @sumitsoni0907 , Do follow the guidelines and complete your work in 1 day. Please go through README file.

Ok
